# -*- coding: utf-8 -*-
"""Copy of 23CD71P01_ASSIGNMENT3_PART1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KnvFElBTzKkRPhc0Ej9stfZJBBJ0U9bw
"""

pip install transformers

pip install torch

from transformers import T5Tokenizer, T5ForConditionalGeneration

model_name = "google/flan-t5-small"  # or "google/flan-t5-base"
tokenizer = T5Tokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name)

model = T5ForConditionalGeneration.from_pretrained(model_name, cache_dir='./cache')
tokenizer = T5Tokenizer.from_pretrained(model_name, cache_dir='./cache')

from transformers import T5Tokenizer, T5ForConditionalGeneration
model_name_small = "google/flan-t5-small"
tokenizer = T5Tokenizer.from_pretrained(model_name_small)
model_small = T5ForConditionalGeneration.from_pretrained(model_name_small)

import pandas as pd

# dataset_path = '/content/NLP_ass_test.tsv'  # Replace with your dataset path
# data = pd.read_csv(dataset_path)
# posts = data['post_column_name']


test_df = pd.read_csv('/content/NLP_ass_test.tsv', sep='\t', header=None)

test_df.columns = ['statement', 'category']

test_df

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# Load small version
tokenizer_small = AutoTokenizer.from_pretrained("google/flan-t5-small")
model_small = AutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-small")

# Load base version
tokenizer_base = AutoTokenizer.from_pretrained("google/flan-t5-base")
model_base = AutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-base")

def zero_shot_classification(model, tokenizer, sentence):
    # Define the prompt to instruct the model
    prompt = f"Classify the following statement as Normal, Hatespeech, or Offensive:\n'{sentence}'"

    # Tokenize and generate output
    inputs = tokenizer(prompt, return_tensors="pt")
    outputs = model.generate(**inputs)
    result = tokenizer.decode(outputs[0], skip_special_tokens=True)

    return result

# Test sentence for zero-shot classification
test_sentence = "This is a sample statement."
classification_result_small = zero_shot_classification(model_small, tokenizer_small, test_df)
print("Zero-shot Classification Result (Small):", classification_result_small)

classification_result_base = zero_shot_classification(model_base, tokenizer_base, test_df)
print("Zero-shot Classification Result (Base):", classification_result_base)

def zero_shot_classification(statement):
    prompt = f"Classify the following statement as 'normal', 'hatespeech', or 'offensive': \"{statement}\""

    # Tokenize and generate output
    inputs = tokenizer(prompt, return_tensors="pt")
    outputs = model_small.generate(**inputs)
    classification = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return classification

# Apply zero-shot inference on the 'statement' column and add results to DataFrame
test_df['predicted_category_zero_shot'] = test_df['statement'].apply(zero_shot_classification)

# Display results
print(test_df[['statement', 'category', 'predicted_category_zero_shot']].head())



# Define few-shot examples to include in the prompt
few_shot_examples = [
    ("I don’t think I'm getting my baby them white 9 h…", "normal"),
    ("Laura Loomer raped me while screaming at me in…", "hatespeech"),
    ("Sex be so good a bitch be slow stroking and cr…", "offensive")
]

# Format the few-shot examples as text for the prompt
few_shot_prompt = "\n".join([f"Statement: \"{ex[0]}\"\nCategory: {ex[1]}" for ex in few_shot_examples])

# Define the few-shot classification function
def few_shot_classification(statement):
    # Construct the prompt with examples followed by the query
    prompt = f"{few_shot_prompt}\n\nClassify the following statement as 'normal', 'hatespeech', or 'offensive': \"{statement}\""

    # Tokenize and generate output
    inputs = tokenizer(prompt, return_tensors="pt")
    outputs = model_small.generate(**inputs)
    classification = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return classification

# Apply few-shot inference on the 'statement' column and add results to DataFrame
test_df['predicted_category_few_shot'] = test_df['statement'].apply(few_shot_classification)

# Display results
print(test_df[['statement', 'category', 'predicted_category_few_shot']].head())

def zero_shot_classification(statement):
    prompt = f"Classify the following statement as 'normal', 'hatespeech', or 'offensive': \"{statement}\""

    # Tokenize and generate output
    inputs = tokenizer(prompt, return_tensors="pt")
    outputs = model_base.generate(**inputs)
    classification = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return classification

# Apply zero-shot inference on the 'statement' column and add results to DataFrame
test_df['predicted_category_zero_shot'] = test_df['statement'].apply(zero_shot_classification)

# Display results
print(test_df[['statement', 'category', 'predicted_category_zero_shot']].head())

# Define few-shot examples to include in the prompt
few_shot_examples = [
    ("I don’t think I'm getting my baby them white 9 h…", "normal"),
    ("Laura Loomer raped me while screaming at me in…", "hatespeech"),
    ("Sex be so good a bitch be slow stroking and cr…", "offensive")
]

# Format the few-shot examples as text for the prompt
few_shot_prompt = "\n".join([f"Statement: \"{ex[0]}\"\nCategory: {ex[1]}" for ex in few_shot_examples])

# Define the few-shot classification function
def few_shot_classification(statement):
    # Construct the prompt with examples followed by the query
    prompt = f"{few_shot_prompt}\n\nClassify the following statement as 'normal', 'hatespeech', or 'offensive': \"{statement}\""

    # Tokenize and generate output
    inputs = tokenizer(prompt, return_tensors="pt")
    outputs = model_base.generate(**inputs)
    classification = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return classification

# Apply few-shot inference on the 'statement' column and add results to DataFrame
test_df['predicted_category_few_shot'] = test_df['statement'].apply(few_shot_classification)

# Display results
print(test_df[['statement', 'category', 'predicted_category_few_shot']].head())