# -*- coding: utf-8 -*-
"""finalnlptosql.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jp_RtFdII1BVk-JRDweQrwUyHyFRrhsd
"""

!CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 --no-cache-dir
!pip install huggingface-hub
!pip install accelerate peft bitsandbytes transformers trl

from huggingface_hub import hf_hub_download

model_name = "TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF"

# Define the name of the model file to download.
model_file = "tinyllama-1.1b-chat-v1.0.Q8_0.gguf"

# Download the model from the Hugging Face Hub and store the
# path to the downloaded file in the `model_path` variable.
model_path = hf_hub_download(model_name, filename=model_file)

# Print a message indicating that the model has been downloaded.
print(f"Model downloaded to: {model_path}")

!pip install llama-cpp-python

from llama_cpp import Llama
from huggingface_hub import hf_hub_download
from huggingface_hub import login
import os

login(token="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")
os.environ["HF_TOKEN"] = "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"

model_name = "TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF"

# Define the name of the model file to download.
model_file = "tinyllama-1.1b-chat-v1.0.Q8_0.gguf"

# Download the model from the Hugging Face Hub and store the
# path to the downloaded file in the `model_path` variable.
model_path = hf_hub_download(model_name, filename=model_file)

# Initialize a `Llama` object with the downloaded model path.
llm = Llama(
    model_path=model_path,

    # Set the number of context tokens.
    n_ctx=512,

    # Set the number of threads to use.
    n_threads=8,

    # Set the number of GPU layers to work with.
    n_gpu_layers=40
)

# Print a message indicating that the Llama object has been initialized.
print("Llama object initialized successfully.")

output = llm(
    # Prompt
    "<|im_start|>user\nAre you a robot?<|im_end|>\n<|im_start|>assistant\n",

    # Set the maximum number of tokens to generate.
    max_tokens=512,

    # Set the stop sequences to indicate the end of the generated text.
    stop=["</s>"],
)

from IPython.display import display, HTML
import html

response_text = output['choices'][0]['text']

display(HTML(f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>LLM Output</title>
    <style>
        body {{
            font-family: 'Roboto', Arial, sans-serif;
            background-color: #f8f9fa;
            padding: 30px;
        }}
        .card {{
            background: #ffffff;
            border-radius: 8px;
            box-shadow: 0 1px 3px rgba(0,0,0,0.15);
            padding: 20px;
            max-width: 900px;
        }}
        h2 {{
            color: #1a73e8; /* Google Blue */
            margin-top: 0;
        }}
        pre {{
            background: #f1f3f4;
            padding: 15px;
            border-radius: 6px;
            white-space: pre-wrap;
            word-wrap: break-word;
            color: #202124;
        }}
    </style>
</head>
<body>
    <div class="card">
        <h2>LLM Response</h2>
        <pre>{html.escape(response_text)}</pre>
    </div>
</body>
</html>
"""))

def chat_template(question, context):
    """
    Creates a chat template for the Llama model.

    Args:
        question: The question to be answered.
        context: The context information to be used for generating the answer.

    Returns:
        A string containing the chat template.
    """

    template = f"""\
    <|im_start|>user
    Given the context, generate an SQL query for the following question
    context:{context}
    question:{question}
    <|im_end|>
    <|im_start|>assistant
    """
    # Remove any leading whitespace characters from each line in the template.
    template = "\n".join([line.lstrip() for line in template.splitlines()])
    return template

from IPython.display import display, HTML
import html

# Example inputs
question = "List all the interview cities for MBA admission at IIM Raipur."
context = "CREATE TABLE onlineadm.interview_city_master (city_name STRING, admission_type STRING)"

# Assuming chat_template just combines them
def chat_template(q, c):
    return f"Question: {q}\nContext: {c}"

# Generate text
template_text = chat_template(question, context)

# Display in styled HTML
display(HTML(f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Chat Template Output</title>
    <style>
        body {{
            font-family: 'Roboto', Arial, sans-serif;
            background-color: #f8f9fa;
            padding: 30px;
        }}
        .card {{
            background: #ffffff;
            border-radius: 10px;
            box-shadow: 0 2px 6px rgba(0,0,0,0.15);
            padding: 25px;
            max-width: 900px;
            margin: auto;
        }}
        h2 {{
            color: #1a73e8;
            margin-top: 0;
        }}
        pre {{
            background: #f1f3f4;
            padding: 20px;
            border-radius: 8px;
            white-space: pre-wrap;
            word-wrap: break-word;
            color: #202124;
            font-size: 14px;
        }}
    </style>
</head>
<body>
    <div class="card">
        <h2>Chat Template Output</h2>
        <pre>{html.escape(template_text)}</pre>
    </div>
</body>
</html>
"""))

output = llm(
    chat_template(question, context),


    # Set the maximum number of tokens to generate.
    max_tokens=512,


    # Set the stop sequences to indicate the end of the generated text.
    stop=["</s>"],
)

# Print the generated text.
print(output['choices'][0]['text'])

from datasets import load_dataset
dataset = load_dataset("csv", data_files="sql-create-context.csv", split="train")

df = dataset.to_pandas()
print(df.head())

def chat_template_for_training(context, answer, question):
    """
    Creates a chat template for training the TinyLlama model.

    Args:
        question: The question to be answered.
        context: The context information to be used for generating the answer.'
        answer: The answer to be generated by the LLM

    Returns:
        A string containing the chat template.
    """

    template = f"""\
    <|im_start|>user
    Given the context, generate an SQL query for the following question
    context:{context}
    question:{question}
    <|im_end|>
    <|im_start|>assistant
    {answer}
    <|im_end|>
    """
    # Remove any leading whitespace characters from each line in the template.
    template = "\n".join([line.lstrip() for line in template.splitlines()])
    return template

import pandas as pd
from datasets import Dataset

# 1. Define df
df = pd.DataFrame({
    "question": ["What is NLP?", "List SQL queries."],
    "answer": ["Natural Language Processing explanation.", "SELECT * FROM table;"]
})

# 2. Add a text column
df["text"] = df.apply(
    lambda x: chat_template_for_training(x["question"], x["answer"], x["question"]),
    axis=1
)

# 3. Convert to Hugging Face Dataset
formatted_data = Dataset.from_pandas(df)

print(df['text'][1])

from transformers import AutoTokenizer

# Define the model to fine-tune
model_id = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

# Load the tokenizer for the specified model.
tokenizer = AutoTokenizer.from_pretrained(model_id)


# Set the padding token to be the same as the end of sentence token.
tokenizer.pad_token = tokenizer.eos_token

!pip install --upgrade bitsandbytes

import bitsandbytes as bnb
print(bnb.__version__)

import torch

if torch.cuda.is_available():
    print("CUDA is available!")
    print(f"Number of CUDA devices: {torch.cuda.device_count()}")
    for i in range(torch.cuda.device_count()):
        print(f"Device {i}: {torch.cuda.get_device_name(i)}")
else:
    print("CUDA is not available. Using CPU instead.")

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

model_id = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True
)

tokenizer = AutoTokenizer.from_pretrained(model_id)

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.float16 # Ensure the model's tensors are loaded as float16
)

print("Model loaded successfully!")

model.config.use_cache = False

# Set the temperature for pretraining to 1.
model.config.pretraining_tp = 1

from peft import LoraConfig

# Define the PEFT configuration.
peft_config = LoraConfig(
    # Set the rank of the LoRA projection matrix.
    r=8,

    # Set the alpha parameter for the LoRA projection matrix.
    lora_alpha=16,

    # Set the dropout rate for the LoRA projection matrix.
    lora_dropout=0.05,

    # Set the bias term to "none".
    bias="none",

    # Set the task type to "CAUSAL_LM".
    task_type="CAUSAL_LM"
)

from transformers import TrainingArguments

# Define the training arguments.
training_args = TrainingArguments(
    # Set the output directory for the training run.
    output_dir="tinyllama-sqllm-v1",

    # Set the per-device training batch size.
    per_device_train_batch_size=1,

    # Set the number of gradient accumulation steps.
    gradient_accumulation_steps=2,

    # Set the optimizer to use.
    optim="paged_adamw_32bit",

    # Set the learning rate.
    learning_rate=2e-4,

    # Set the learning rate scheduler type.
    lr_scheduler_type="cosine",

    # Set the save strategy.
    save_strategy="epoch",

    # Set the logging steps.
    logging_steps=10,

    # Set the number of training epochs.
    num_train_epochs=2,

    # Set the maximum number of training steps.
    max_steps=500,

    # Enable fp16 training.
    fp16=False, # Disable FP16
    bf16=True,  # Enable BF16
    report_to="none"
)

from trl import SFTTrainer

# Initialize the SFTTrainer.
trainer = SFTTrainer(
    # Set the model to be trained.
    model=model,

    # Set the training dataset.
    train_dataset=formatted_data,

    # Set the PEFT configuration.
    peft_config=peft_config,

    # Set the training arguments.
    args=training_args
)
trainer.train()

from peft import AutoPeftModelForCausalLM, PeftModel

# Load the pre-trained model.
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    load_in_8bit=False,
    device_map="auto",
    trust_remote_code=True
)

# Load the PEFT model from a checkpoint.
model_path = "/content/tinyllama-sqllm-v1/checkpoint-500"
peft_model = PeftModel.from_pretrained(model, model_path, from_transformers=True, device_map="auto")

# Wrap the model with the PEFT model.
model = peft_model.merge_and_unload()

import re
question = "List all the interview cities for MBA admission at IIM Raipur."


with open("context_interview_city.txt", "r") as f:
    context = f.read()


# Add explicit instruction for filtering MBA
prompt = chat_template(
    question,
    context + "\n-- Write a SQL SELECT query that lists only the cities where admission_type is 'MBA'."
)

inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

output = model.generate(
    **inputs,
    max_new_tokens=64,
    do_sample=False,
    eos_token_id=tokenizer.eos_token_id,
    pad_token_id=tokenizer.eos_token_id,
)

generated_ids = output[0][inputs["input_ids"].shape[-1]:]
raw_sql = tokenizer.decode(generated_ids, skip_special_tokens=True)

# This regex will extract the first SQL statement that starts with SELECT
match = re.search(r"(SELECT\s.+?;)", raw_sql, re.IGNORECASE | re.DOTALL)

if match:
    sql = match.group(1).strip()
else:
    # fallback if regex fails
    sql = ""


# Display in styled HTML (same as before)
from IPython.display import display, HTML
import html

display(HTML(f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>NLP → SQL Output</title>
    <style>
        body {{
            font-family: 'Segoe UI', Arial, sans-serif;
            background-color: #f4f6f9;
            padding: 40px;
        }}
        .card {{
            background: #ffffff;
            border-radius: 12px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.12);
            padding: 30px;
            max-width: 900px;
            margin: auto;
        }}
        h2 {{
            color: #1a73e8;
            margin-top: 0;
        }}
        .label {{
            font-weight: 600;
            color: #5f6368;
            margin-top: 20px;
        }}
        .box {{
            background: #f1f3f4;
            padding: 15px;
            border-radius: 8px;
            margin-top: 6px;
            font-size: 14px;
            color: #202124;
        }}
        pre {{
            background: #0b5394;
            color: #ffffff;
            padding: 18px;
            border-radius: 8px;
            font-size: 14px;
            overflow-x: auto;
        }}
    </style>
</head>
<body>
    <div class="card">
        <h2>NLP → SQL Generation</h2>

        <div class="label">Question</div>
        <div class="box">{html.escape(question)}</div>


        <div class="label">Generated SQL</div>
        <pre>{html.escape(sql)}</pre>
    </div>
</body>
</html>
"""))