# -*- coding: utf-8 -*-
"""languageTranslate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1um-D5LKWDa0x0MiGKA_WifGlZnN1uln8
"""

pip install -U huggingface_hub transformers sentencepiece accelerate

!pip install -U IndicTransToolkit

# Install compatible versions
!pip uninstall -y transformers IndicTransToolkit
!pip install transformers==4.46.3 sentencepiece accelerate
!pip install git+https://github.com/AI4Bharat/IndicTrans2.git

!pip install -U --no-cache-dir IndicTransToolkit

# ================================
# 1. Install required packages
# ================================
!pip install -q -U transformers==4.46.3 sentencepiece accelerate IndicTransToolkit

import os
from getpass import getpass
from huggingface_hub import login

# Enter your Hugging Face token
token = getpass("Enter your Hugging Face token: ")

# Save token for this runtime
os.environ["HF_TOKEN"] = token

# Login
login(token=token)

print("Hugging Face login successful")

# ============================================================
# Bengali -> English Translation using IndicTrans2
# ============================================================

# Install compatible packages
!pip install -q "transformers==4.46.3" "huggingface_hub<1.0" sentencepiece
!pip install -q git+https://github.com/AI4Bharat/IndicTrans2.git

# ============================================================
# 1. Hugging Face authentication
# ============================================================

# ============================================================
# 2. Imports
# ============================================================

import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from IndicTransToolkit.processor import IndicProcessor

# ============================================================
# 3. Model
# ============================================================

MODEL_NAME = "ai4bharat/indictrans2-indic-en-1B"

device = "cuda" if torch.cuda.is_available() else "cpu"

print("Device:", device)

# ============================================================
# 4. Load tokenizer
# ============================================================

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME,
    trust_remote_code=True,
    token=token
)

# ============================================================
# 5. Load model
# ============================================================

model = AutoModelForSeq2SeqLM.from_pretrained(
    MODEL_NAME,
    trust_remote_code=True,
    token=token
).to(device)

model.eval()

processor = IndicProcessor(inference=True)

# ============================================================
# 6. Bengali input
# ============================================================

text = [
    "রোগীর আজ জ্বর এবং মাথা ব্যথা করছে।"
]

src_lang = "ben_Beng"
tgt_lang = "eng_Latn"

# ============================================================
# 7. Preprocessing
# ============================================================

batch = processor.preprocess_batch(
    text,
    src_lang=src_lang,
    tgt_lang=tgt_lang
)

inputs = tokenizer(
    batch,
    padding="longest",
    truncation=True,
    return_tensors="pt"
).to(device)

# ============================================================
# 8. Translation
# ============================================================

with torch.no_grad():

    output = model.generate(
        **inputs,
        max_length=256,
        num_beams=5
    )

# ============================================================
# 9. Decode
# ============================================================

output = tokenizer.batch_decode(
    output,
    skip_special_tokens=True
)

translation = processor.postprocess_batch(
    output,
    lang=tgt_lang
)

# ============================================================
# 10. Result
# ============================================================

print("\nBengali :", text[0])
print("English :", translation[0])